#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible_galaxy_role_hadoop

- name: "Hadoop | Create a group"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.group:
    name: hadoop
    state: present

- name: "Hadoop | Download jdk tarball file"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.get_url:
    url: https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
    dest: /usr/local/src

- name: "Hadoop | Unpack jdk tarball file"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.unarchive:
    remote_src: yes
    src: /usr/local/src/openjdk-11.0.2_linux-x64_bin.tar.gz
    dest: /opt

- name: "Hadoop | Download binary"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.get_url:
    url: https://dlcdn.apache.org/hadoop/common/hadoop-3.4.1/hadoop-3.4.1.tar.gz
    dest: /usr/local/src

- name: "Hadoop | Download signature file"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.get_url:
    url: https://dlcdn.apache.org/hadoop/common/hadoop-3.4.1/hadoop-3.4.1.tar.gz.asc
    dest: /usr/local/src

- name: "Hadoop | Download key file"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.get_url:
    url: https://downloads.apache.org/hadoop/common/KEYS
    dest: /tmp/hadoop-keys

- name: "Hadoop | Install GPG"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    pkg:
      - gpg
    state: present
    update_cache: yes

- name: "Hadoop | Import GPG public key and verify binary"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.shell:
    cmd: |
      gpg --import /tmp/hadoop-keys
      gpg --verify /usr/local/src/hadoop-3.4.1.tar.gz.asc /usr/local/src/hadoop-3.4.1.tar.gz
  register: hadoop_gpg_verify

- name: "Hadoop | Succeeded to verify"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.debug:
    msg: "GPG検証が成功しました。"
  when: hadoop_gpg_verify.rc == 0

- name: "Hadoop | Failed to verify"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.debug:
    msg: "GPG検証が失敗しました。"
  when: hadoop_gpg_verify.rc != 0

- name: "Hadoop | Unpack binary"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  ansible.builtin.unarchive:
    remote_src: yes
    src: /usr/local/src/hadoop-3.4.1.tar.gz
    dest: /opt
